#!/bin/bash

echo "🔄 Force Resume MongoDB Atlas Cluster"
echo "====================================="
echo ""
echo "⚠️  Since Atlas UI is the only reliable way to resume,"
echo "    here's what you need to do:"
echo ""
echo "📍 STEP 1: Open this URL in browser:"
echo "   https://cloud.mongodb.com/v2/65f8a9b4c5d2e3f4a5b6c7d8#/clusters"
echo ""
echo "📍 STEP 2: Find 'Cluster0' and click on it"
echo ""
echo "📍 STEP 3: Look for one of these:"
echo "   • 'Resume' button (top right)"
echo "   • '...' menu → 'Resume Cluster'"
echo "   • Status showing 'Paused' with resume option"
echo ""
echo "⏰ STEP 4: Wait 2-3 minutes after clicking Resume"
echo ""
echo "✅ STEP 5: Run this to verify connection:"
echo "   node resume-cluster.js"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Alternative: Use local MongoDB (already configured)"
echo "   Your .env is already set to: mongodb://localhost:27017/farmview_ai"
echo "   Just run: npm start"
echo ""
